name: Lint
on: push

jobs:
  lint:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ruby/setup-ruby@v1.62.0
        with:
          bundler-cache: true
      - run: bundle exec rubocop
