name: Lint
on: push

jobs:
  lint:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-ruby@v1.1.1
        with:
          ruby-version: '2.7'
      - uses: actions/cache@v1.1.0
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-
      - run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 4
      - run: bundle exec rubocop
