name: Lint
on: push

jobs:
  lint:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@master
        with:
          ruby-version: 2.7.0
      - run: gem install bundler
      - env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 4
        run: bundle install
      - run: bundle exec rubocop
