name: Test
on: push

jobs:
  test:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@master
        with:
          ruby-version: 2.6.3
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec
